name: Aula de GCS (PUC CAMPINAS)
on: push
jobs:
  primeiro:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event_name }} foi disparado"
      - run: echo " No ${{runner.os}}"
      - run: echo " Repositorio ${{github.repository}} na branch ${{github.ref}}"
      
      - name: Mostrar rodadndo
        run: echo  "teste"
      - name: Mostrar rodadndo
        run: echo "${{ github.event_name }} foi disparado"
    
 # segundo:
 ##   runs-on: windows-latest
 #   name: First
 #   steps:      
 #     - name: Criando Variaveis de ambiente
 #       env:
 #         VAR1: Isto é
 ##         VAR2: GitHUB ACtions
 #       run: echo $VAR1 $VAR2
      
 
     






