name: Aula de GCS (PUC CAMPINAS)
on: push
jobs:
  primeiro:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event_name }} foi disparado"
      - run: echo " No ${{runner.os}}"
      - run: echo " Repositorio ${{github.repository}} na branch ${{github.ref}}"
      
      - name: Checkout o repositorio
        uses: actions/checkout@v3
      
      - name: Mostrar rodadndo
        run: echo  "teste"
      - name: Mostrar rodadndo
        run: echo "${{ github.event_name }} foi disparado"
      - name: listando conteudo
        run: ls -la ${{ github.workspace }}
      
  Segundo_exemplo:
    runs-on: ubuntu-latest

    strategy:
     matrix:
      node-version: [14.x]
      # versao 10 e 12 desatualizadas e nao mais em produção
    steps:
      - uses: actions/checkout@v3 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }} 

      - run: npm ci         
      - run: npm run build --if-present
      - run: npm test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
      - name: Enviando ao Glitch
        uses: kanadgupta/glitch-sync@main
        with:
          auth-token: '${{ secrets.authToken }}' 
          project-id: '${{ secrets.projectId }}'

# 
#
#

 # segundo:
 ##   runs-on: windows-latest
 #   name: First
 #   steps:      
 #     - name: Criando Variaveis de ambiente
 #       env:
 #         VAR1: Isto é
 ##         VAR2: GitHUB ACtions
 #       run: echo $VAR1 $VAR2
      
 
     






